// @generated by Diesel - run `diesel migration run` then `diesel print-schema` to regenerate
// This file matches migrations/20250101000000_depatreon_schema

diesel::table! {
    creators (service_object_id) {
        service_object_id -> Text,
        creator_address -> Text,
        name -> Text,
        description -> Text,
        avatar_blob_id -> Nullable<Text>,
        suins_name -> Nullable<Text>,
        total_subscribers -> Int4,
        total_posts -> Int4,
        revenue_mist -> Int8,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    events_log (id) {
        id -> Int8,
        event_type -> Text,
        checkpoint -> Int8,
        tx_digest -> Text,
        data -> Jsonb,
        timestamp -> Timestamptz,
    }
}

diesel::table! {
    posts (id) {
        id -> Int4,
        service_object_id -> Text,
        post_id -> Int4,
        title -> Text,
        metadata_blob_id -> Nullable<Text>,
        data_blob_id -> Nullable<Text>,
        required_tier -> Int4,
        created_at_ms -> Int8,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    subscriptions (id) {
        id -> Int4,
        subscriber_address -> Text,
        service_object_id -> Text,
        tier_level -> Int4,
        expires_at_ms -> Int8,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    tiers (id) {
        id -> Int4,
        service_object_id -> Text,
        tier_level -> Int4,
        name -> Text,
        price_mist -> Int8,
        duration_ms -> Int8,
    }
}

diesel::joinable!(posts -> creators (service_object_id));
diesel::joinable!(subscriptions -> creators (service_object_id));
diesel::joinable!(tiers -> creators (service_object_id));

diesel::allow_tables_to_appear_in_same_query!(
    creators,
    events_log,
    posts,
    subscriptions,
    tiers,
);
